### ISSUE TITLE
[USER STORY]: As a user, I want to add a comment to a photo

### ISSUE THREAD

**Issue by amanda6mard** [martinsenecal/SOEN341#17]
## About this story 
**Priority**: High
**Story Points**: 5
**Risk**: [Low]

**Description**: 
Users need the ability to comment on photos they view on their feed and photos they view on other people's profiles.

**Acceptance Test**
- User can type a comment into a form on the photo page
- On submit, the comment gets added to the post objects comments

**Sub-Tasks/Steps**

- [x] Design the 'add comment' UI
- [x] Plan for comments in database
- [x]  Ability to remove comments
- [x]  Validation of input (back-end)
- [x] Timestamp comments
- [x] UI/Front End

**Linked to Issue**: #13
