### ISSUE TITLE
[USER STORY]: As a user, I want to reply to comments on photos

### ISSUE THREAD

**Issue by amanda6mard** [martinsenecal/SOEN341#19]
## About this story 
**Priority**: Low
**Story Points**: Fibonacci Sequence: 3
**Risk**: [Medium]

**Description**: 
Users can reply to comments and replies will be shown in a new thread from the original comment.

**Acceptance Test**
- Reply button available on each comment
- On click, reply button shows a reply form
- On submit, replies gets added to the comment objects replies
- Replies are listed on the page as a thread on the comment itself

**Sub-Tasks/Steps**
- [ ] Design reply UI
- [ ] Plan for replies in the database
- [ ] Ability to edit replies
- [ ] Ability to remove replies
- [ ] Validation of input (front-end and back-end)
- [ ] Timestamp replies

**Linked to Issue**: #13
