### ISSUE TITLE
[USER STORY]: As a user, I want to upload a photo

### ISSUE THREAD

**Issue by kimdera** [martinsenecal/SOEN341#20]
## About this story 
**Priority**: [High]
**Story Points**: 5
**Risk**: [Low]

**Description**: 
Users need to be able to choose and upload a photo to the web application.

**Acceptance Test**
- User can select a photo from their file browser or by dragging and dropping into an outlined box
- On submit, photo gets added to the user’s profile

**Sub-Tasks/Steps**
- [x] Set up the AWS S3 bucket
- [x] Design the 'upload photo' UI
- [x] Ability to upload a photo
- [x] Considering a default size for uploaded photo

**Linked to Issue**: #12
