### ISSUE TITLE
[USER STORY]: As a user, I want to add a photo description when uploading a photo

### ISSUE THREAD

**Issue by kimdera** [martinsenecal/SOEN341#21]
## About this story 
**Priority**: [High]
**Story Points**: 3
**Risk**: [Low]

**Description**: 
Ability to add a description to a photo before uploading it to the user feed. 

**Acceptance Test**
- User can type description in the photo upload form
- Blank descriptions are allowed and do no cause upload problems
- On submit, the description is attached to the photo and is shown in the feed and on the photo page

**Sub-Tasks/Steps**
- [x] Design the 'add a description' UI
- [x] Add the description in the database (connection with user obj and uploaded photo)
- [x] Test the feature.

**Linked to Issue**: #12
