### ISSUE TITLE
[USER STORY]: As a user, I want to view new following posts on the feed

### ISSUE THREAD

**Issue by kimdera** [martinsenecal/SOEN341#22]
## About this story 
**Priority**: [High]
**Story Points**: 2
**Risk**: [Medium]

**Description**: 
The user will be able to post a picture and the picture will be automatically added to their feed.
In addition, the user can see their following new posts on the feed.
Posts will be ordered by the time of the post.

**Acceptance Test**
-The feed displays the photos (in reverse post order, newest at the top) posted by the user and people the user is following. 

**Sub-Tasks/Steps**
- [x] Design the feed UI
- [x] Timestamp the time of post
- [x] Adding x new posts to the user's feed
- [x] Creating post APIs

**Linked to Issue**: #12
