### ISSUE TITLE
[USER STORY]: As a user I would like to search for another user

### ISSUE THREAD

**Issue by gkillick** [martinsenecal/SOEN341#23]
## About this story 
**Priority**: [Medium]
**Story Points**: 5
**Risk**: [Medium]

**Description**: 
The user will be able to search and find other users by their username within the application. 

**Acceptance Test**
- User can search for usernames from the search bar in the nav
- Search bar suggests usernames as the user types
- On click of a username, the user is brought to the selected person’s profile

**Sub-Tasks/Steps**
- [ ] create UI for search page with a search field and the list below to contain search results
- [ ] create request in node.js that will respond with user object matching the search criteria
- [ ] Handle user input with the key event that sends a request to the backend 
- [ ] Handle response from backend by placing user objects formatted into the list below the search bar

**Linked to Issue**: [#14]
