### ISSUE TITLE
[USER STORY]: As a user I would like to be able to follow/unfollow a user

### ISSUE THREAD

**Issue by gkillick** [martinsenecal/SOEN341#24]
## About this story 
**Priority**: [High]
**Story Points**: 2
**Risk**: [Medium]

**Description**: 
User will be able to follow a user listed below the search field. 

**Acceptance Test**
- Clicking the follow/unfollow button:
-- adds/removes the relevant username from the users following list
-- adds/removes the user from the relevant username’s follower list
- Style and words on the button toggle on click.
- On profiles, follower/following counts and lists should be updated on click
- On feed, photos from new people the user is following should now be included/ommited

**Sub-Tasks/Steps**
- [x] Create follow requests in backend that will add the selected user id to the current users following and respond with success/failure
- [x] Create un-follow requests in the backend
- [x] Use response of the request to indicate the current user is now following the selected user

**Linked to Issue**: [#14 ]
