### ISSUE TITLE
[USER STORY]: As a user I would like to be able to see my followers and who I am following

### ISSUE THREAD

**Issue by gkillick** [martinsenecal/SOEN341#25]
## About this story 
**Priority**: [High]
**Story Points**:  3
**Risk**: [Low]

**Description**: 
The user will be able to view followers and following. 

**Acceptance Test**
- On profile, the count of followers/following is shown
- Count is formatted so that numbers <1000 appear in full, and numbers >999 appear in thousand format (1.5K)
- On profile, lists of usernames followers/following can be viewed by clicking on the respective count
- Lists include follow/unfollow button for each username(when not showing the user’s username)

**Sub-Tasks/Steps**
- [ ] UI create component for listing out users
- [ ] Create request to back end sending the current user's id and returning a list of user objects who follow the current user
- [ ] Create request to back end sending current user's id and returning a list of user objects who the current user follows
- [ ] Respond to either request by populating the list with the returned user objects

**Additional context**

**Linked to Issue**: [#14]
