### ISSUE TITLE
[USER STORY]: As a user I would like to be able to register

### ISSUE THREAD

**Issue by MilitsaB** [martinsenecal/SOEN341#26]
## About this story 
**Priority**: [High]
**Story Points**: 5
**Risk**: [Medium]

**Description**: 
The user will be able to create an account.

**Acceptance Test**
- Link to the signup page is provided on the login page
- Users can fill out the form on the signup page
- Form verifies the appropriate password
- Form verifies unique usernames
- On submit, if all verifications are successful, new user is created

**Sub-Tasks/Steps**
- [x] Design the 'add new user' UI 
- [x] Add user in the database
- [x] Create a profile.
- [x] Create API Routes for User Registration
- [x] Create User Model
- [x] Connect FrontEnd to API Register
- [x] Fixed Auth for Permission.
- [x] Testing

**Linked to Issue**: #15
