### ISSUE TITLE
[USER STORY]: As a user I would like to be able to login

### ISSUE THREAD

**Issue by MilitsaB** [martinsenecal/SOEN341#27]
## About this story 
**Priority**: [High]
**Story Points**: 3
**Risk**: [High]

**Description**: 
The user will be able to login onto his account. 

**Acceptance Test**
- User can login from the login in page
- Error messages are shown for unsuccessful attempts
- On successful login, the user has access to all pages on the site
- Accessing pages other than the login and signup page without being logged in is prevented

**Sub-Tasks/Steps**
- [x] Design the 'Sign-in' UI
- [x] Create request to back end sending the input from user's id and password and comparing it with the information from the database.
- [x] If authentication information is correct, create request to back end sending current user's id and returning his profile.
- [x] If authentication information is incorrect, request user to input his information again.
- [x] Fixed Auth for Permission.
- [x] Testing

**Linked to Issue**: #15
