### ISSUE TITLE
[USER STORY]: As a user I would like to have a feed

### ISSUE THREAD

**Issue by MilitsaB** [martinsenecal/SOEN341#30]
## About this story 
**Priority**: High
**Story Points**: 8
**Risk**: [Medium]

**Description**: 
The user will be able to see other users' photos.

**Acceptance Test**
- Feed page exists
- User needs to be logged in to access it

**Sub-Tasks/Steps**
- [x] Design the 'user feed' UI with multiple components.
- [x] Create a request to the back end to return photos posted by other users.
- [x] Create an API in the backend to get all the photos from all users.

**Linked to Issue**: #15
