### ISSUE TITLE
[USER STORY]: As a user, I would like to be able to edit my profile.

### ISSUE THREAD

**Issue by martinsenecal** [martinsenecal/SOEN341#61]
## About this story

**Priority**: Medium
**Story Points**: 5
**Risk**: Low

**Description**:
The user would be able to edit his own profile. The form will let the user change his name, profile picture, and description. 

**Acceptance Test**
-  User can change their name and bio
- User can select a photo from their file browser or by dragging and dropping into an outlined box
- On click, new information for profile should appear in profile page

**Sub-Tasks/Steps**

- [x] Design and code the form in the UI
- [x] Add Edit Option in the navbar and in the profile of the logged-in user.
- [x] Create the put API in the backend.
- [x] Add a connection to the s3 bucket for the profile picture.

**Linked to Issue**: [#15]
