### ISSUE TITLE
[USER STORY]:As a user, I want to like a photo.

### ISSUE THREAD

**Issue by martinsenecal** [martinsenecal/SOEN341#74]
## About this story

**Priority**: Medium
**Story Points**: 3
**Risk**: Low

**Description**:
Add a like for a photo and make sure it is stored in the database.

**Acceptance Test**
- Like button available on all photos: profile page, feed, photo page
- On liked photos, like button appears as a full red heart
- On click, like is registered in the database
- On click, the button toggles to its "liked" state

**Sub-Tasks/Steps**

- [x] Create the API in the backend to like a photo, and add it to the post model.
- [ ] Connect the backend to the frontend.
- [ ] Create the UI-like component.
- [ ] Make sure the like button is in red if a post was like. 

**Linked to Issue**: [#73]
