### ISSUE TITLE
[USER STORY]:As a user, I want to unlike a photo.

### ISSUE THREAD

**Issue by martinsenecal** [martinsenecal/SOEN341#75]
## About this story

**Priority**: Medium
**Story Points**: 1
**Risk**: Low

**Description**:
Add a dislike for a photo and make sure it is stored in the database.

**Acceptance Test**
- (Un)like button available on all photos: profile page, feed, photo page
- On photos that have **not** been liked, the button appears as an empty black heart
- On click, like is removed from the database
- On click, button toggles to its "unliked" state

**Sub-Tasks/Steps**

- [ ] Create the API in the backend to like a photo, and add it to the post model.
- [ ] Connect the backend to the frontend.
- [ ] Create the UI-like component.
- [ ] Make sure the like button is in white if a post was unlike. 

**Linked to Issue**: [#73]
